### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by RaveWolffun** [DingoDjango/snAutosave#20]
Hi, I had this mod with SN1 and worked great. Thanks for upgrading to SN2... I tested now after seeing it on Discord, and it Autosaved as soon as the game loaded, then keeps doing like a double save about every 15 seconds... Yes, seconds, not minutes as stated in the "Next Save" prompt.
I do have other mods installed, but never experienced the issues stated by others.

Cheers.

**Comment by DingoDjango** [comment]
I got a similar report from another user. Will look into it this weekend.

**Comment by DingoDjango** [comment]
> Hi, I had this mod with SN1 and worked great. Thanks for upgrading to SN2... I tested now after seeing it on Discord, and it Autosaved as soon as the game loaded, then keeps doing like a double save about every 15 seconds... Yes, seconds, not minutes as stated in the "Next Save" prompt. I do have other mods installed, but never experienced the issues stated by others.
> 
> Cheers.

If you go to the config file, which value is written under MinutesBetweenAutosaves?

If you change the value in the file or through the Configuration Manager mod, does this problem go away?

**Comment by RaveWolffun** [comment]
> 

There is no Config file... I checked when I exited the game previously and saw none. Only the .dll and the Language folder are there, and then deleted the folder. After exiting now and checking in, and saw your query, I added it in again, and there is still no Config file... I loaded the game assuming that maybe it will create one on start, but there isn't any.

**Comment by DingoDjango** [comment]
The .dll and Languages folder are in the plugins directory. The config file is in the config directory...

I'm assuming you deleted QMods and installed only BepInEx as is recommended for Subnautica 2.0+

**Comment by RaveWolffun** [comment]
Got you... Did a quick grab for you, all looks good.

Autosave Using Time Intervals = true
Autosave On Sleep = true **(Not Sleeping)**
Minutes Between Autosaves = 15
Minimum Player Health Percent = 0.25 **(Health 100%)**
Show Save Names = true
Maximum Autosave Slots = 3
Hardcore Mode = false
Quicksave Hotkey = F9
Save All Files = true

When I loaded the game now it did the Autosave again on start... Not sure if that is default.
Busy timing it now.

**Comment by RaveWolffun** [comment]
Start
18:38
25:61

Okay, I think I know what's happening... It's the 3 saves one after the other. For me, it takes just over a minute to complete all 3. I assume the more mods the longer it will take.
Busy running the game now for the 15min run. I will update you the 15 min is up.

**Comment by RaveWolffun** [comment]
Saved now on 4:46... and didn't notice the 30 sec countdown.

**Comment by DingoDjango** [comment]
What do you mean "3 saves one after the other"? The game autosaves the maximum amount of saves at once?

**Comment by RaveWolffun** [comment]
Correct. but only on startup.
So as per above... Start (save), ±18 sec (save), ±25 sec (Save)... then the next was 4+ min after, then 10+ min after that.

**Comment by RaveWolffun** [comment]
Trying to troubleshoot... Times are inconsistent. Health is good, Food and Water is good.
Haven't been able to pin-point anything yet.

Another interesting thing just happened... It Autosaved while I was in Inventory and Battery console trying to swop out a battery when it decided to autosave. When the autosave was done my mouse lost focus of the game. The keyboard still worked fine but couldn't gain focus of the game with the mouse. Had to exit and reload.

**Comment by RaveWolffun** [comment]
I have a huge list of Mods.
I would help troubleshoot by starting fresh and only adding one at a time, but I'm just a bit stretched for time right now.
[Export_Q-Dir.txt](https://github.com/DingoDjango/snAutosave/files/10449959/Export_Q-Dir.txt)

**Comment by DingoDjango** [comment]
If you have a couple minutes to test a fresh save with just autosave+bepinex it could indicate if there is a conflict.

One user already reported conflicts but autosave worked fine when used on its own.

**Comment by RaveWolffun** [comment]
**### Troubleshooting:**
Busy testing now... 
I will keep re-editing this comment with each new development and testing phase.

1. Backed up and Cleaned out the Plugins folder and started a fresh game.
2. Played ± 10min of standard game then Saved.
3. Added Autosave Mod.
4.

**Comment by DingoDjango** [comment]
Thanks for the detailed report! I will see if I can replicate this behaviour...

**Comment by RaveWolffun** [comment]
Just started again with a clean slate... Full Activity
This is all in one run with Timer set to 5 min.

01) 01:01
02) 00:15
03) 00:40
04) 00:27
05) 02:58
06) 00:29
07) 03:02
08) 00:16
09) 05:10
10) 05:05
11) 05:02

Will try again tomorrow.

**Comment by DingoDjango** [comment]
I would hold off on trying again. I think I will have another build done by the evening.

**Comment by DingoDjango** [comment]
Version 2.0.3 is ready, I hope it fixes this issue

**Comment by RaveWolffun** [comment]
> Version 2.0.3 is ready, I hope it fixes this issue

Cool, will test it out in a bit.

**Comment by RaveWolffun** [comment]
So far so good...
I kept the setting at 5min, and played for 20 min with saves at each respective 5min mark.
Also no saves after loading the game.

I tested with this mod only... Going to go to the extreme with all other mods first. If there are any issue then I will start will 1 or 2 mods at a time to isolate.

**Comment by DingoDjango** [comment]
You might get an autosave near load with v2.0.3

I adjusted the initial autosave schedule in the next version to account for longer load times (large save and/or mod folder). So if you want to check back later for the new version.

**Comment by RaveWolffun** [comment]
> You might get an autosave near load with v2.0.3
> 
> I adjusted the initial autosave schedule in the next version to account for longer load times (large save and/or mod folder). So if you want to check back later for the new version.

This is awesome... I tested with all mods running and so far no issue. The 5min timer goes to about 5:30'ish... So not bad at all. That minor discrepancy could simply be down to system speeds or CPU clock, etc. Unless the 30sec countdown is not being deducted from the 5min marker?!

**Comment by DingoDjango** [comment]
More than likely you just entered/exited a hatch (habitat, seamoth etc.) which delays autosave. That plus timer rounding which always moves things a few seconds.

**Comment by RaveWolffun** [comment]
Thanks for the work and effort. It's greatly appreciated.
