### ISSUE TITLE
PDA lock and constant resaving

### ISSUE THREAD

**Issue by BananaDude508** [DingoDjango/snAutosave#21]
Newest Version
When my pda is open when the notification says finished saving, i get locked in the pda. i cant close it, look around or interact with anything, onle move with wasd.
also im getting saves every 30-60 seconds

**Comment by DingoDjango** [comment]
Can you provide a mod list? Preferrably with mod versions, at least for bepinex and any mods you suspect might be conflicting.

**Comment by DingoDjango** [comment]
Is this bug happening with the latest version?
