### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Yanuut** [DingoDjango/snAutosave#4]
French.json
{
  "AutosaveWarning": "Préparation de la sauvegarde automatique dans {0} secondes.",
  "AutosaveStarting": "Début de la séquence de sauvegarde automatique...",
  "AutosaveEnding": "Sauvegarde automatique effectuée. Prochaine sauvegarde automatique dans {0} secondes.",
  "AutosaveInProgress": "Sauvegarde automatique en cours. Impossible de sauvegarder automatiquement à nouveau pour l'instant."
}

**Comment by DingoDjango** [comment]
Thank you.
